### ISSUE TITLE
初始化错误

### ISSUE THREAD

**Issue by zhaj08** [shiyinghan/UVCAndroid#12]
请帮忙看一下是什么问题，谢谢
openUVCCamera:
                                                                                                    java.lang.IllegalArgumentException: Failed to initialize audio/mp4a-latm, error 0xfffffffe
                                                                                                    	at android.media.MediaCodec.native_setup(Native Method)
                                                                                                    	at android.media.MediaCodec.<init>(MediaCodec.java:1811)
                                                                                                    	at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1777)
                                                                                                    	at com.herohan.uvcapp.VideoCapture.initVideoAudioEncoder(VideoCapture.java:257)
                                                                                                    	at com.herohan.uvcapp.VideoCapture.<init>(VideoCapture.java:204)
                                                                                                    	at com.herohan.uvcapp.CameraInternal.openUVCCamera(CameraInternal.java:239)
                                                                                                    	at com.herohan.uvcapp.CameraInternal.openCamera(CameraInternal.java:191)
                                                                                                    	at com.herohan.uvcapp.CameraConnectionService$CameraConnection.openCamera(CameraConnectionService.java:310)
                                                                                                    	at com.herohan.uvcapp.CameraHelper.lambda$openCamera$6$com-herohan-uvcapp-CameraHelper(CameraHelper.java:253)
                                                                                                    	at com.herohan.uvcapp.CameraHelper$$ExternalSyntheticLambda6.run(Unknown Source:4)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by shiyinghan** [comment]
我修改了一下VideoCapture，你更新一下本库的代码，重新运行一下试试
