### ISSUE TITLE
Native Crash : Thread Name: 'MediaCodec_loop',signal 6 (SIGABRT), code -6 (SI_TKILL),

### ISSUE THREAD

**Issue by zhouyeliang** [shiyinghan/UVCAndroid#18]
关闭摄像头，释放资源的时候闪退崩溃：
"CameraHelper" prio=6 tid=16 Native
  | group="" sCount=0 dsCount=0 obj=0x12df80d0 self=0xd1464200
  | sysTid=1928 nice=0 cgrp=default sched=0/0 handle=0xd1e7f920
  | state=? schedstat=( 0 0 0 ) utm=0 stm=0 core=0 HZ=100
  | stack=0xd1d7d000-0xd1d7f000 stackSize=1038KB
  | held mutexes=
  at android.media.MediaCodec.native_release(Native method)
  at android.media.MediaCodec.release(MediaCodec.java:1810)
  at com.herohan.uvcapp.VideoCapture.releaseAudioInputResource(VideoCapture.java:493)
  at com.herohan.uvcapp.VideoCapture.releaseResources(VideoCapture.java:483)
  at com.herohan.uvcapp.VideoCapture.release(VideoCapture.java:475)
  at com.herohan.uvcapp.CameraInternal.closeCamera(CameraInternal.java:278)

**Comment by shiyinghan** [comment]
看起来是系统组件MediaCodec释放失败的问题，而且是Native Crash，也没办法用try catch捕获
