### ISSUE TITLE
部分手机不出图黑屏，请问怎么解决

### ISSUE THREAD

**Issue by 798146512** [shiyinghan/UVCAndroid#57]
我们的产品有640*480   160*120  
我们现在采用640*480   但是部分手机在640*480分辨率的情况下黑屏，改成160*120的时候可以，请问是什么原因造成的呢？

**Comment by shiyinghan** [comment]
有Logcat日志吗

**Comment by Qdafengzi** [comment]
> 有Logcat日志吗

 java.lang.RuntimeException: failed to open USB device(has no permission) cameraKey:2002
                                                                                       	at com.herohan.uvcapp.CameraConnectionService$CameraConnection.selectDevice(CameraConnectionService.java:217)
                                                                                       	at com.herohan.uvcapp.CameraHelper.lambda$selectDevice$0(CameraHelper.java:99)
                                                                                       	at com.herohan.uvcapp.CameraHelper.$r8$lambda$cQ953StbhnC5cVbMwGfXcdCBFro(Unknown Source:0)
                                                                                       	at com.herohan.uvcapp.CameraHelper$$ExternalSyntheticLambda17.run(D8$$SyntheticClass:0)
                                                                                       	at android.os.Handler.handleCallback(Handler.java:888)
                                                                                       	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                       	at android.os.Looper.loop(Looper.java:213)
                                                                                       	at android.os.HandlerThread.run(HandlerThread.java:67)
