### ISSUE TITLE
本地so库加载错误

### ISSUE THREAD

**Issue by wangweitmac777** [shiyinghan/UVCAndroid#69]
我把libuvccamera本地集成到我的项目里，然后编写逻辑代码，就遇到加载错误
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libjpeg-turbo212.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.serenegiant.usb.UVCCamera.<clinit>(UVCCamera.java:83)
        at com.herohan.uvcapp.CameraInternal.openUVCCamera(CameraInternal.java:221)
        at com.herohan.uvcapp.CameraInternal.openCamera(CameraInternal.java:191)
        at com.herohan.uvcapp.CameraConnectionService$CameraConnection.openCamera(CameraConnectionService.java:310)
        at com.herohan.uvcapp.CameraHelper.lambda$openCamera$6$CameraHelper(CameraHelper.java:253)
        at com.herohan.uvcapp.-$$Lambda$CameraHelper$XS7OkjOidNGW0N8N78LHdAbIi3w.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)

这个是什么原因啊

**Comment by zzy-33** [comment]
看下你主项目的Build.gradle里有没有设置jnilib的路径
